repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: check-yaml
      args: [--unsafe]
    - id: check-toml
    - id: detect-private-key
#-   repo: local
#    hooks:
#    -   id: mypy
#        name: mypy
#        entry: mypy
#        exclude: ^tests
#        language: python
#        types: [python]
#        require_serial: true
#        verbose: true
